try:
  print('try start')
  print(param)
except Exception as e:
  print(e)
